input data:
  truth file: data/test_truthNdemographics.csv
  test scores: data/test_scores.csv
  uid column: case_name
  truth column: truth

output:
  qwk:
    save: false
    file prefix: output/delta_kappas_
  eod:
    save: true
    file prefix: output/eod_
  aaod:
    save: true
    file prefix: output/aaod_

numeric_cols:
  age_binned:
    raw column: age
    bins: [ 0, 18, 30, 40, 50, 65, 75, 85, .inf ]
    labels: ['<18', '18-29', '30-39', '40-49', '50-64', '65-74', '75-84', '85+']

plot:
  custom_orders:
    age_binned: [ '18-29', '30-39', '40-49', '50-64', '65-74', '75-84', '85+' ]
    sex: [ 'Male', 'Female' ]
    race: [ 'White', 'Black or African American', 'Asian', 'Other' ]
    ethnicity: [ 'Hispanic or Latino', 'Not Hispanic or Latino' ]
    intersectional_race_ethnicity: [ 'White and Not Hispanic or Latino', 'Not White or HisapanicLatino' ]
